Andrew
telestech/telestech.github.io pull request #3
Opened 2024-12-14 17:39 UTC by iuthao

2024-12-14 22:39 UTC, Indoriajs requested changes
Review the comments and make the necessary changes.

2024-12-14 22:39 UTC, Indoriajs commented on app/src/Components/Footer/Footer.js
No hard-coded strings. Move contact information to a different file (`xml`, `json`).

2024-12-14 22:39 UTC, Indoriajs commented on app/src/Home/Home.js
> +
Move to a different file, and query from those. No hard-coded strings for items that may change with transalation.

2024-12-14 22:39 UTC, Indoriajs commented on app/src/Home/Home.js
> +    );
Having all the definitions in the same file will make it hard to maintain.
Move it to either:

```
Home
 |-> Components
    |-> <component>.js 
```

Or just create various `<component>.js` files under the `Home` directory.

2024-12-14 22:39 UTC, Indoriajs commented on app/src/Process/Process.js
> +);`;
...
No, just no.

Instead of passing it as a string, you can pass a function instead. That would be safer and would adhere to standards.

2024-12-14 22:39 UTC, Indoriajs commented on app/tailwind.config.js
> +    },
Store colors in a different file and then query from it. 
This way, we only have to change it at one place,  if needed.

2024-12-16 22:55 UTC, Indoriajs commented
Can all the other changes be addressed as well?

2025-01-02 19:38 UTC, closed without merging

2025-01-02 19:38 UTC, shortbunny commented
changes have been added in other branches